//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLblogCard1
    {
        public int ID { get; set; }
        public string Card1Resim { get; set; }
        public string Card1Baslik { get; set; }
        public string Card1AtBaslik { get; set; }
        public string Card1Tarih { get; set; }
        public string Card1Aciklama { get; set; }
    }
}
